### ISSUE TITLE
GraphQL 테스트용 playground 추가

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-server#31]
쿼리 추가, 변경 등으로 GraphQL 스키마를 바꾸게 되면 새 API가 잘 동작하는지 테스트해 볼 필요가 있습니다. 이럴 때 굳이 클라이언트를 실행하지 않고도 브라우저에서 GraphQL 쿼리를 수동으로 입력해 테스트해 볼 수 있도록 해 주는 것이 playground입니다.

이 이슈에서는 `http://127.0.0.1:8080/graphql/playground`처럼 서버의 /graphql/playground로 접속한 경우 async-graphql이 제공하는 playground 기능을 이용하여 GraphQL 테스트가 가능하도록 합니다. [`playground_source`](https://docs.rs/async-graphql/latest/async_graphql/http/fn.playground_source.html)로 playground를 만들고, warp에서 /graphql/playground를 인식하여 playground를 실행하도록 하면 됩니다.

**Comment by BLYKIM** [comment]
/graphql/playground로 접속을 한다는게 새로운 playground IDE를 띄우는건가요 아니면 쿼리를 같이 줘서 실행시키는 개념인가요?

**Comment by msk** [comment]
> /graphql/playground로 접속을 한다는게 새로운 playground IDE를 띄우는건가요 아니면 쿼리를 같이 줘서 실행시키는 개념인가요?

서버가 `http://127.0.0.1:8080`에서 돌고 있을 때, 브라우저 주소창에 `http://127.0.0.1:8080/graphql/playground`라고 입력하는 것을 말합니다.

**Comment by BLYKIM** [comment]
네 주소창에 입력을 한 이후에 playground가 실행되고 쿼리를 입력하여 테스트 할 수 있게 하는게 맞나요?
