### ISSUE TITLE
GitHub에서 pull requests를 가져올 때 assignees 정보도 가져오기

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-server#59]
GitHub에서 pull requests를 가져오는 GraphQL query (pull_requests.graphql)에는 number와 title만 가져오도록 되어 있습니다. 여기에 assignees의 username까지 가져오도록 query를 고치고 관련 코드를 변경합니다. 아래 내용이 query의 node 부분에 추가되어야 합니다.

```graphql
assignees(last: 15) {
  nodes {
    login
  }
}
```

이 이슈에서는 pull requests를 가져오는 부분만 수정하고, 데이터베이스에 저장하는 부분은 별도 이슈에서 다루겠습니다.

**Comment by ChriSangHoon** [comment]
[http://graphql.github.com](http://graphql.github.com) 에서 확인해보면 query issues에서는 assignees 데이터가 나오지만, query pullRequests에는 assignees 데이터가 보이지 않는데, pull_reqeusts.graphql 파일에 위의 코드를 추가하는 것이 맞는지 확인 부탁드립니다!

**Comment by msk** [comment]
아래 그림은 http://graphql.github.com/ 에서 Explorer로 들어가서 pullRequests를 본 화면인데요, 맨 밑에 보면 assignees가 있습니다.

![explorer-pullrequests](https://user-images.githubusercontent.com/19195/185034016-f1e960ef-4294-4d53-acee-942651b7bd88.png)
