### ISSUE TITLE
클라이언트에서 이슈 요청시 종료되지 않은 이슈만 돌려주기

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-server#70]
클라이언트쪽 첫 화면에 표시되는 이슈는 아직 종료되지 않은 이슈로 제한합니다. 그러려면 GitHub에서 이슈를 가져올 때 [`closedAt`](https://docs.github.com/en/graphql/reference/interfaces#closable)의 값을 가져와서 스토리지에 저장해놓고, `issues` GraphQL API를 처리할 때 해당 값이 `None`이 아닌 이슈만 보내줘야 합니다.

**Comment by BLYKIM** [comment]
`Some`이 아닌 이슈만 보내겠습니다
